<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Vehicle;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        $vehicles = [
            [
                'brand' => 'Mercedes-Benz', 'model' => 'Classe C', 'version' => 'C 220d AMG Line',
                'vehicle_type' => 'berline', 'condition' => 'occasion', 'seller_type' => 'concessionnaire',
                'year' => 2022, 'mileage' => 32000, 'price' => 38900, 'ancien_prix' => 42500,
                'fuel_type' => 'diesel', 'power_hp' => 200, 'power_kw' => 147,
                'transmission' => 'automatique', 'drive' => 'propulsion',
                'exterior_color' => 'Noir obsidien', 'interior_color' => 'Beige',
                'interior_material' => 'cuir', 'air_conditioning' => 'climatisation_automatique',
                'seats' => 5, 'doors' => 4, 'country' => 'CH', 'city' => 'Genève',
                'status' => 'actif', 'vat_status' => 'recuperable', 'price_type' => 'fixe',
                'service_book' => true, 'warranty' => true, 'non_smoker' => true,
                'previous_owners' => 1, 'export_available' => true,
                'exterior_extras' => ['Jantes alliage 18"', 'Toit ouvrant', 'Phares LED'],
                'interior_extras' => ['Navigation', 'Caméra recul', 'Sièges chauffants'],
                'description' => 'Superbe Mercedes Classe C en parfait état, entretien Mercedes complet, première main.',
                'vin' => 'WDD2050011F123456',
            ],
            [
                'brand' => 'BMW', 'model' => 'Série 3', 'version' => '320d xDrive M Sport',
                'vehicle_type' => 'berline', 'condition' => 'occasion', 'seller_type' => 'concessionnaire',
                'year' => 2021, 'mileage' => 58000, 'price' => 34500, 'ancien_prix' => null,
                'fuel_type' => 'diesel', 'power_hp' => 190, 'power_kw' => 140,
                'transmission' => 'automatique', 'drive' => '4x4',
                'exterior_color' => 'Blanc alpinweiss', 'interior_color' => 'Noir',
                'interior_material' => 'cuir', 'air_conditioning' => 'climatisation_automatique',
                'seats' => 5, 'doors' => 4, 'country' => 'CH', 'city' => 'Lausanne',
                'status' => 'actif', 'vat_status' => 'recuperable', 'price_type' => 'fixe',
                'service_book' => true, 'warranty' => false, 'non_smoker' => true,
                'previous_owners' => 2, 'export_available' => true,
                'exterior_extras' => ['Pack M Sport', 'Jantes 19"', 'Rétros chauffants'],
                'interior_extras' => ['iDrive 7', 'HUD', 'Sièges sport'],
                'description' => 'BMW Série 3 xDrive, idéale pour l\'hiver suisse, carnet d\'entretien BMW.',
                'vin' => 'WBA5R1C07LFJ12345',
            ],
            [
                'brand' => 'Audi', 'model' => 'A4', 'version' => '2.0 TDI S line',
                'vehicle_type' => 'berline', 'condition' => 'occasion', 'seller_type' => 'concessionnaire',
                'year' => 2020, 'mileage' => 74000, 'price' => 28900, 'ancien_prix' => 31000,
                'fuel_type' => 'diesel', 'power_hp' => 150, 'power_kw' => 110,
                'transmission' => 'automatique', 'drive' => 'traction_avant',
                'exterior_color' => 'Gris daytona', 'interior_color' => 'Noir',
                'interior_material' => 'tissu', 'air_conditioning' => 'climatisation_automatique',
                'seats' => 5, 'doors' => 4, 'country' => 'CH', 'city' => 'Zurich',
                'status' => 'actif', 'vat_status' => 'recuperable', 'price_type' => 'fixe',
                'service_book' => true, 'warranty' => false, 'non_smoker' => false,
                'previous_owners' => 2, 'export_available' => false,
                'exterior_extras' => ['Pack S line', 'Phares Xenon'],
                'interior_extras' => ['MMI Navigation', 'Bluetooth'],
                'description' => 'Audi A4 S line bien équipée, révision faite récemment.',
                'vin' => 'WAUZZZ8K7LA012345',
            ],
            [
                'brand' => 'Volkswagen', 'model' => 'Tiguan', 'version' => '2.0 TDI Highline 4Motion',
                'vehicle_type' => 'suv_pickup', 'condition' => 'occasion', 'seller_type' => 'concessionnaire',
                'year' => 2022, 'mileage' => 41000, 'price' => 33500, 'ancien_prix' => null,
                'fuel_type' => 'diesel', 'power_hp' => 190, 'power_kw' => 140,
                'transmission' => 'automatique', 'drive' => '4x4',
                'exterior_color' => 'Argent reflet', 'interior_color' => 'Beige',
                'interior_material' => 'cuir', 'air_conditioning' => 'climatisation_automatique',
                'seats' => 5, 'doors' => 5, 'country' => 'CH', 'city' => 'Berne',
                'status' => 'actif', 'vat_status' => 'recuperable', 'price_type' => 'fixe',
                'service_book' => true, 'warranty' => true, 'non_smoker' => true,
                'previous_owners' => 1, 'export_available' => true,
                'exterior_extras' => ['Toit panoramique', 'Jantes 18"'],
                'interior_extras' => ['Discover Pro', 'Sièges chauffants', 'Caméra 360°'],
                'description' => 'VW Tiguan 4Motion première main, toutes options, état irréprochable.',
                'vin' => 'WVGZZZ5NZPW123456',
            ],
            [
                'brand' => 'Porsche', 'model' => 'Cayenne', 'version' => 'S E-Hybrid',
                'vehicle_type' => 'suv_pickup', 'condition' => 'occasion', 'seller_type' => 'concessionnaire',
                'year' => 2021, 'mileage' => 29000, 'price' => 79900, 'ancien_prix' => 89000,
                'fuel_type' => 'hybride_plug_in', 'power_hp' => 462, 'power_kw' => 340,
                'transmission' => 'automatique', 'drive' => '4x4',
                'exterior_color' => 'Noir jet', 'interior_color' => 'Bordeaux',
                'interior_material' => 'cuir', 'air_conditioning' => 'climatisation_automatique',
                'seats' => 5, 'doors' => 5, 'country' => 'CH', 'city' => 'Genève',
                'status' => 'actif', 'vat_status' => 'recuperable', 'price_type' => 'fixe',
                'service_book' => true, 'warranty' => true, 'non_smoker' => true,
                'previous_owners' => 1, 'export_available' => true,
                'exterior_extras' => ['Pack Sport Design', 'Toit panoramique', 'Jantes 21"'],
                'interior_extras' => ['PCM 4.0', 'BOSE Sound', 'Sièges ventilés', 'HUD'],
                'description' => 'Exceptionnel Porsche Cayenne hybride, full options, prise en charge garantie constructeur.',
                'vin' => 'WP1ZZZ9YZMDA12345',
            ],
            [
                'brand' => 'Toyota', 'model' => 'RAV4', 'version' => '2.5 Hybrid AWD-i Style',
                'vehicle_type' => 'suv_pickup', 'condition' => 'occasion', 'seller_type' => 'concessionnaire',
                'year' => 2023, 'mileage' => 18000, 'price' => 39900, 'ancien_prix' => null,
                'fuel_type' => 'hybride_rechargeable', 'power_hp' => 222, 'power_kw' => 163,
                'transmission' => 'automatique', 'drive' => '4x4',
                'exterior_color' => 'Blanc nacré', 'interior_color' => 'Noir',
                'interior_material' => 'tissu', 'air_conditioning' => 'climatisation_automatique',
                'seats' => 5, 'doors' => 5, 'country' => 'CH', 'city' => 'Lausanne',
                'status' => 'actif', 'vat_status' => 'recuperable', 'price_type' => 'fixe',
                'service_book' => true, 'warranty' => true, 'non_smoker' => true,
                'previous_owners' => 1, 'export_available' => false,
                'exterior_extras' => ['Jantes 18"', 'Caméra recul'],
                'interior_extras' => ['Navigation', 'Apple CarPlay', 'Android Auto'],
                'description' => 'Toyota RAV4 hybride quasi neuf, faible kilométrage, garantie Toyota 2 ans.',
                'vin' => 'JTMRW3FV4PD123456',
            ],
            [
                'brand' => 'Renault', 'model' => 'Mégane', 'version' => '1.5 dCi Intens',
                'vehicle_type' => 'berline', 'condition' => 'occasion', 'seller_type' => 'particulier',
                'year' => 2020, 'mileage' => 88000, 'price' => 14900, 'ancien_prix' => 16500,
                'fuel_type' => 'diesel', 'power_hp' => 115, 'power_kw' => 85,
                'transmission' => 'manuelle', 'drive' => 'traction_avant',
                'exterior_color' => 'Bleu iron', 'interior_color' => 'Noir',
                'interior_material' => 'tissu', 'air_conditioning' => 'climatisation',
                'seats' => 5, 'doors' => 4, 'country' => 'FR', 'city' => 'Annemasse',
                'status' => 'actif', 'vat_status' => 'non_recuperable', 'price_type' => 'fixe',
                'service_book' => false, 'warranty' => false, 'non_smoker' => false,
                'previous_owners' => 3, 'export_available' => false,
                'exterior_extras' => ['Jantes alliage'],
                'interior_extras' => ['Navigation', 'Bluetooth'],
                'description' => 'Renault Mégane fiable et économique, idéale en ville.',
                'vin' => 'VF1BFB00163123456',
            ],
            [
                'brand' => 'Land Rover', 'model' => 'Range Rover Sport', 'version' => 'P400e HSE Dynamic',
                'vehicle_type' => 'suv_pickup', 'condition' => 'occasion', 'seller_type' => 'concessionnaire',
                'year' => 2022, 'mileage' => 35000, 'price' => 68500, 'ancien_prix' => 74000,
                'fuel_type' => 'hybride_plug_in', 'power_hp' => 404, 'power_kw' => 297,
                'transmission' => 'automatique', 'drive' => '4x4',
                'exterior_color' => 'Gris corris', 'interior_color' => 'Beige',
                'interior_material' => 'cuir', 'air_conditioning' => 'climatisation_automatique',
                'seats' => 5, 'doors' => 5, 'country' => 'CH', 'city' => 'Genève',
                'status' => 'actif', 'vat_status' => 'recuperable', 'price_type' => 'fixe',
                'service_book' => true, 'warranty' => true, 'non_smoker' => true,
                'previous_owners' => 1, 'export_available' => true,
                'exterior_extras' => ['Toit panoramique', 'Jantes 22"', 'Barres de toit'],
                'interior_extras' => ['Meridian Sound', 'Pivi Pro', 'Sièges massants', 'HUD'],
                'description' => 'Range Rover Sport hybride rechargeable, finition HSE Dynamic luxueuse.',
                'vin' => 'SALWA2RE7NA123456',
            ],
            [
                'brand' => 'Volvo', 'model' => 'XC60', 'version' => 'T8 Recharge AWD R-Design',
                'vehicle_type' => 'suv_pickup', 'condition' => 'neuf', 'seller_type' => 'concessionnaire',
                'year' => 2024, 'mileage' => 500, 'price' => 64900, 'ancien_prix' => null,
                'fuel_type' => 'hybride_rechargeable', 'power_hp' => 390, 'power_kw' => 287,
                'transmission' => 'automatique', 'drive' => '4x4',
                'exterior_color' => 'Bleu denim', 'interior_color' => 'Gris',
                'interior_material' => 'cuir', 'air_conditioning' => 'climatisation_automatique',
                'seats' => 5, 'doors' => 5, 'country' => 'CH', 'city' => 'Berne',
                'status' => 'actif', 'vat_status' => 'recuperable', 'price_type' => 'fixe',
                'service_book' => true, 'warranty' => true, 'non_smoker' => true,
                'previous_owners' => 0, 'export_available' => false,
                'exterior_extras' => ['Pack R-Design', 'Jantes 21"', 'Toit ouvrant'],
                'interior_extras' => ['Google intégré', 'Bowers & Wilkins', 'Sièges ventilés'],
                'description' => 'Volvo XC60 neuf démonstration, garantie constructeur 5 ans, 0 km compteur.',
                'vin' => 'YV1UZA8V1P1234567',
            ],
            [
                'brand' => 'Kia', 'model' => 'EV6', 'version' => 'GT-Line AWD 77.4 kWh',
                'vehicle_type' => 'berline', 'condition' => 'occasion', 'seller_type' => 'concessionnaire',
                'year' => 2023, 'mileage' => 22000, 'price' => 41500, 'ancien_prix' => 46000,
                'fuel_type' => 'electrique', 'power_hp' => 325, 'power_kw' => 239,
                'transmission' => 'automatique', 'drive' => '4x4',
                'exterior_color' => 'Vert glacé', 'interior_color' => 'Noir',
                'interior_material' => 'tissu', 'air_conditioning' => 'climatisation_automatique',
                'seats' => 5, 'doors' => 5, 'country' => 'CH', 'city' => 'Zurich',
                'status' => 'actif', 'vat_status' => 'recuperable', 'price_type' => 'fixe',
                'service_book' => true, 'warranty' => true, 'non_smoker' => true,
                'previous_owners' => 1, 'export_available' => true,
                'exterior_extras' => ['Jantes 20"', 'Toit vitré'],
                'interior_extras' => ['Head-Up Display', 'Chargeur sans fil', 'Bose Sound'],
                'description' => 'Kia EV6 AWD électrique 100%, charge rapide 800V, autonomie 500 km.',
                'vin' => 'KNDC3DLC3P5123456',
            ],
            [
                'brand' => 'Honda', 'model' => 'CR-V', 'version' => 'e:HEV Advance AWD',
                'vehicle_type' => 'suv_pickup', 'condition' => 'occasion', 'seller_type' => 'concessionnaire',
                'year' => 2023, 'mileage' => 15000, 'price' => 42900, 'ancien_prix' => null,
                'fuel_type' => 'hybride_essence', 'power_hp' => 184, 'power_kw' => 135,
                'transmission' => 'automatique', 'drive' => '4x4',
                'exterior_color' => 'Rouge premium', 'interior_color' => 'Gris',
                'interior_material' => 'tissu', 'air_conditioning' => 'climatisation_automatique',
                'seats' => 5, 'doors' => 5, 'country' => 'CH', 'city' => 'Zurich',
                'status' => 'actif', 'vat_status' => 'recuperable', 'price_type' => 'fixe',
                'service_book' => true, 'warranty' => true, 'non_smoker' => true,
                'previous_owners' => 1, 'export_available' => false,
                'exterior_extras' => ['Jantes 18"', 'Caméra 360°'],
                'interior_extras' => ['Honda Sensing', 'Apple CarPlay', 'Sièges chauffants'],
                'description' => 'Honda CR-V hybride, très économique, idéal pour la famille.',
                'vin' => 'MRHRU489XPJ123456',
            ],
            [
                'brand' => 'Ford', 'model' => 'Mustang Mach-E', 'version' => 'GT AWD Extended Range',
                'vehicle_type' => 'suv_pickup', 'condition' => 'occasion', 'seller_type' => 'concessionnaire',
                'year' => 2022, 'mileage' => 27000, 'price' => 46500, 'ancien_prix' => 52000,
                'fuel_type' => 'electrique', 'power_hp' => 487, 'power_kw' => 358,
                'transmission' => 'automatique', 'drive' => '4x4',
                'exterior_color' => 'Rouge rapid red', 'interior_color' => 'Noir',
                'interior_material' => 'cuir', 'air_conditioning' => 'climatisation_automatique',
                'seats' => 5, 'doors' => 5, 'country' => 'CH', 'city' => 'Genève',
                'status' => 'actif', 'vat_status' => 'recuperable', 'price_type' => 'fixe',
                'service_book' => true, 'warranty' => true, 'non_smoker' => true,
                'previous_owners' => 1, 'export_available' => true,
                'exterior_extras' => ['Jantes 20"', 'Toit panoramique'],
                'interior_extras' => ['Écran SYNC 4 15.5"', 'Bang & Olufsen', 'Sièges chauffants'],
                'description' => 'Ford Mustang Mach-E GT, performances SUV électrique, autonomie 480 km.',
                'vin' => '3FMTK4SX6NMA12345',
            ],
        ];

        foreach ($vehicles as $data) {
            $brandName = $data['brand'];
            unset($data['brand']);

            $brand = Brand::where('name', $brandName)->first();
            if (!$brand) continue;

            Vehicle::firstOrCreate(
                ['vin' => $data['vin']],
                array_merge($data, ['brand_id' => $brand->id])
            );
        }
    }
}
